### ISSUE TITLE
Screen flickering on Intel graphics

### ISSUE THREAD

**Issue by ghost** [rsu-client/rsu-client#130] opened 2017-09-10 00:14 UTC
@HikariKnight 

I am using a MacBook Pro with Ubuntu in a virtualbox and I am getting black screen flickering on Runescape 3.  Have you implemented the patch for this or if you haven't can you please implement it?

**Comment by HikariKnight** [comment] 2017-09-12 06:12
@soaringowl2145 Nope as its not caused by my client as this client only launches the legacy client, after that its all hands off, very unlikely that will be fixed.
Also the game was never meant to be run through a virtual machine. which might explain the issues you get from it

**Closed** 2018-10-28 13:28 UTC
Labels: invalid, wontfix
