### ISSUE TITLE
Bug on openSUSE Tumbleweed; Java applet starts but is not loaded properly

### ISSUE THREAD

**Issue by fusion809** [rsu-client/rsu-client#92] opened 2016-02-21 19:34 UTC
Hi,

I have used this excellent program on the following platforms without this particular issue:
- Arch Linux
- Fedora 22
- Manjaro Linux
- Sabayon Linux

yet for some reason most of the time (occasionally I get lucky and the Java applet loads fine) on openSUSE Tumbleweed when I start RSU under KDE Plasma 5 the Java applet loads (no GTK window shown [here](https://camo.githubusercontent.com/b9ff749a3d45f33e890b0e1d7626b0c7130ffcfd/687474703a2f2f692e696d6775722e636f6d2f7a576e347353512e706e67), though. Oddly enough this window does not seem to load at all) but then it pops up, minimized in the top-left hand corner of the screen as shown in this screenshot:

![](http://imgur.com/YmE3NyA.png)

and when I maximize this Java applet window I get this blank, black window:

![](http://imgur.com/y24YjJL.png)

Waiting seems to make no difference, RS fails to load in this applet. If you're wondering how I installed RSU well I followed the instructions in the README of this repo. I ran:

``` bash
sudo zypper in perl "perl(List::MoreUtils)" "perl(Config::IniFiles)" "perl(Archive::Extract)"
```

downloaded and extracted the Bit Rock installer for 4.3.4 and ran it as standard non-root user. Then to start RSU I clicked the `.desktop` file for RSU, namely the one in `~/.local/share/applications/runescape.desktop`. 

Thanks for your time,
Brenton

**Comment by fusion809** [comment] 2016-02-21 19:37
@HikariKnight sorry forgot to notify ya

**Comment by fusion809** [comment] 2016-02-21 19:56
Ah, I found the cause of why no RSU client (and rather the Java applet starts) starts. I didn't have [`perl-Wx`](https://software.opensuse.org/package/perl-Wx) package installed. Please amend the:

```bash
sudo zypper in perl "perl(List::MoreUtils)" "perl(Config::IniFiles)" "perl(Archive::Extract)"
```
command for installing the dependencies to:

```bash
sudo zypper in perl "perl(List::MoreUtils)" "perl(Config::IniFiles)" "perl(Archive::Extract)" perl-Wx
```

This issue does not fix the Java applet issue, though.

**Comment by fusion809** [comment] 2016-02-21 20:04
If it helps here is my runescape.prm file:
```perl
-Djava.class.path=jagexappletviewer.jar
-Dcom.jagex.config=http://www.runescape.com/k=3/l=$(Language:0)/jav_config.ws
-Xmx2048m
-Xss2m
-Dsun.java2d.noddraw=true

jagexappletviewer
```

here is my rsu-settings file:
```bash
#!/usr/bin/perl -w

# This script is provided for legacy support

# Use the FindBin module so we can get the scriptname
use FindBin;

# Get the script name
my $scriptname = $FindBin::Script;

# Get the scriptdir
my $scriptdir = $FindBin::RealBin;

# Remove rsu- from the name
$scriptname =~ s/rsu-//;

# If scriptname is runescape and no parameters are passed
if ($scriptname =~ /^runescape$/ && "@ARGV" eq '')
{
	# Try launch the launcher (if not it will fallback to starting runescape directly)
	system "$scriptdir/rsu/rsu-query";
}
# Else
else
{
	# Launch the actual script
	system "$scriptdir/rsu/rsu-query client.launch.$scriptname @ARGV";
}
```

**Comment by ivanpu** [comment] 2016-02-21 20:15
Hmm... you shouldn't edit [rsu-settings](https://github.com/HikariKnight/rsu-client/blob/master/runescape/rsu-settings) file, it's part of the client.
All your configurations should be in [`rsu-client/runescape/share/configs/`](https://github.com/HikariKnight/rsu-client/tree/master/runescape/share/configs), or `~/.config/runescape/share/configs/`, depending on installation.

What Java (vendor && version) do you use?

**Comment by fusion809** [comment] 2016-02-21 20:20
I didn't edit that file, I was sharing it in case it was helpful (like in case it wasn't set properly by the BitRock installer). My Java version/vendor is something I'm not 100% sure about but I'm guessing that running `java -version` will show this info, if so here is the output of this command:
```bash
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-02-08-164123.abuild.jdk9-47d6462e514b)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-02-08-164123.abuild.jdk9-47d6462e514b, mixed mode)
```

**Comment by ivanpu** [comment] 2016-02-21 20:29
OpenJDK 9!?
I would not recommend to use it yet, unless you are helping with its development.
For example, take a look at [their schedule](http://openjdk.java.net/projects/jdk9/):
>2016/05/26		Feature Complete
...
2017/03/23		General Availability

Latest stable is 8, and last time I heard about it, it still had few issues with RS.
I myself use 7, and it works well.

**Comment by fusion809** [comment] 2016-02-21 20:32
OK, so does this mean I have to uninstall OpenJDK 9? Or can I just adjust the settings of RSU to use OpenJDK 7? Is this is done via going to `Settings` (in the RSU client window) and setting "Preferred Java to use" to 7-openjdk? If so I've already tried that and it failed to get the RS Java applet to start properly. And yes, after changing that setting, I tried closing my existing RSU windows and

**Comment by ivanpu** [comment] 2016-02-21 20:34
Yes, in the launcher settings... you can also try to select `custom-java` and then fill the path to openjdk7 `java` executable.
Also, what do you get in the console from running the client?

**Comment by fusion809** [comment] 2016-02-21 20:46
[Here](http://paste2.org/MJbVYa7I) is the output from running `runescape` from the command-line. OK, this is proving difficult... Do you know where the executable is for openjdk7 on openSUSE? I've installed the [`java-1_7_0-openjdk`](https://software.opensuse.org/package/java-1_7_0-openjdk) package and running:
```bash
rpm -ql java-1_7_0-openjdk | grep /usr/bin
```
returns nada...

**Comment by ivanpu** [comment] 2016-02-21 20:58
>```bash
rpm -ql java-1_7_0-openjdk | grep /usr/bin
```

Try `rpm -ql java-1_7_0-openjdk | grep java` instead...
Judging from your ouput, it should be in `/usr/lib64/jvm/jre-1.7.0-openjdk/bin/`.

And I've seen nothing suspicious in the client output.
Except, maybe, `cairo-nogl` - it was workaround, that is not required already at least for ArchLinux.

**Comment by fusion809** [comment] 2016-02-21 20:59
That `rpm -ql java-1_7_0-openjdk | grep java` returns:

```bash
/usr/lib64/jvm/java-1.7.0-openjdk-1.7.0/jre/lib/amd64
/usr/lib64/jvm/java-1.7.0-openjdk-1.7.0/jre/lib/amd64/libicedtea-sound.so
/usr/lib64/jvm/java-1.7.0-openjdk-1.7.0/jre/lib/amd64/libjavagtk.so
/usr/lib64/jvm/java-1.7.0-openjdk-1.7.0/jre/lib/amd64/libjsoundalsa.so
/usr/lib64/jvm/java-1.7.0-openjdk-1.7.0/jre/lib/amd64/libsplashscreen.so
/usr/lib64/jvm/java-1.7.0-openjdk-1.7.0/jre/lib/amd64/xawt
/usr/lib64/jvm/java-1.7.0-openjdk-1.7.0/jre/lib/amd64/xawt/libmawt.so
/usr/lib64/jvm/java-1.7.0-openjdk-1.7.0/jre/lib/pulseaudio.properties
```

**Comment by ivanpu** [comment] 2016-02-21 21:21
Just use the ``Browse`` button, and see if you have `/usr/lib64/jvm/jre-1.7.0-openjdk/bin/java` file.

**Comment by fusion809** [comment] 2016-02-21 21:24
I have that file and setting that as my custom-java path, saving that setting, closing RSU, restarting it (and yes I checked in settings to see that this setting stuck) and pressing "Play Now" launches the RS Java applet with the same bug as I started with.

**Comment by ivanpu** [comment] 2016-02-21 21:27
Strange... let's poke @HikariKnight :point_right:

**Comment by fusion809** [comment] 2016-02-21 21:32
You sure the label "issue" still fits this topic? Sounds more like a bug to me, unless I am unclear on the definitions used for each label.

**Comment by ivanpu** [comment] 2016-02-21 21:51
It definitely does not deserves a `bug` label - the problem is after launching Jagex code = not _our_ bug.
And... I myself not quite sure what the `issue` label stands for, but this issue does look like an issue to me :no_mouth:

**Comment by HikariKnight** [comment] 2016-02-22 10:54
@fusion809 @ivanpu hello i was summoned?
I cant find anything in the output either, could we get an updated one from after you told it to use OpenJDK7?

I have never seen this issue before though.

**Comment by fusion809** [comment] 2016-02-23 07:22
Oddly enough I rebooted and this error seems (not confident enough to declare this from the rooftops, though, rofl) to have subsided. Might have been a Java issue, so I'll close this issue until (and if) it resurfaces.

**Comment by fusion809** [comment] 2016-02-25 02:02
The issue striked again. See for the output: http://paste2.org/MCw4ag52.

**Comment by ivanpu** [comment] 2016-02-26 14:17
Try to (re)move `~/runescape/rsu/3rdParty/linux/cairo-nogl`.
Not sure what else we can try...

**Comment by HikariKnight** [comment] 2018-10-28 13:43
no info for years, closing this

**Closed by HikariKnight** 2018-10-28 13:43 UTC
Labels: issue
